toolbar:
  - styleselect | bold italic | undo redo
  - image | link | codesample | preview | wordcount | media | code
plugins:
  - image
  - link
  - codesample
  - preview
  - wordcount
  - media
  - autosave
  - code